In [1]:
import numpy as np
import pandas as pd
import scipy.stats as stats
import matplotlib.pyplot as plt
import sklearn

In [2]:
# -*- coding: utf-8 -*-

In [3]:
df = pd.read_csv('raw_data/2015.csv', encoding='CP949', index_col =False)

/Applications/anaconda2/lib/python2.7/site-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [12]:
df.weather = pd.read_csv('raw_data/weather2015.csv', encoding='CP949', index_col =False)

In [5]:
df.pollution = pd.read_csv('raw_data/pollution2015.csv', encoding='CP949', index_col =False)

In [ ]:
#print(df)
#print(df.weather)
#print(df.pollution)

In [ ]:
df.columns
df.weather.columns
df.pollution.columns

In [6]:
df=df.loc[df["location"].isnull() == False,:]

In [ ]:
#df.renamed = df.rename(index=str, columns={"날짜": "date", "역번호": "id", "역명": "name", "구분":"category", "05~06": "5", "06~07": "6", "07~08": "7", "08~09": "8", "09~10": "9", "10~11": "10", "11~12": "11", "12~13": "12", "13~14": "13", "14~15": "14", "15~16": "15", "16~17": "16", "17~18": "17", "18~19": "18", "19~20": "19", "20~21": "20", "21~22": "21", "22~23": "22", "23~24": "23", "24~": "24"})
#df.renamed = df.rename(index=str, columns={"날짜": "date", "역번호": "id", "역명": "name", "구분":"category", "05~06": 5, "06~07": 6, "07~08": 7, "08~09": 8, "09~10": 9, "10~11": 10, "11~12": 11, "12~13": 12, "13~14": 13, "14~15": 14, "15~16": 15, "16~17": 16, "17~18": 17, "18~19": 18, "19~20": 19, "20~21": 20, "21~22": 21, "22~23": 22, "23~24": 23, "24~": 24})

In [7]:
#https://github.com/pandas-dev/pandas/issues/17676
df.melted=pd.melt(df, id_vars=["date", "id", "name", "category", "location"], value_vars=["5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24"], var_name="time")
#df.melted=pd.melt(df, id_vars=["date", "id", "name", "category", "location"], value_vars=[5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24], var_name="time")

In [8]:
df.melted[['time']]=df.melted[['time']].apply(pd.to_numeric)

In [9]:
df.melted=df.melted[df.melted.loc[:,"time"]<24]

In [ ]:
#df.melted[['value']]=df.melted[['value']].apply(pd.to_numeric)

In [ ]:
df.weather[['time']]=df.weather[['time']].apply(pd.to_numeric)

In [ ]:
#df.renamed.set_index('')

In [10]:
print(df.melted)

               date    id            name category location  time  value
0        2015-01-01   150        서울역(150)        0       중구     5    441
1        2015-01-01   151         시청(151)        0       중구     5    101
2        2015-01-01   152         종각(152)        0      종로구     5    898
3        2015-01-01   153       종로3가(153)        0      종로구     5    371
4        2015-01-01   154       종로5가(154)        0      종로구     5     57
5        2015-01-01   155        동대문(155)        0      종로구     5    130
6        2015-01-01   156        신설동(156)        0     동대문구     5     95
7        2015-01-01   157        제기동(157)        0     동대문구     5    102
8        2015-01-01   158    청량리(지하)(158)        0     동대문구     5    273
9        2015-01-01   159        동묘앞(159)        0      종로구     5     48
10       2015-01-01   201         시청(201)        0       중구     5     39
11       2015-01-01   202      을지로입구(202)        0       중구     5    149
12       2015-01-01   203      을지로3가(203)        0       중구     5     30
13       2015-01-01   204      을지로4가(204)        0       중구     5     30
14       2015-01-01   205  동대문역사문화공원(205)        0       중구     5    125
15       2015-01-01   206         신당(206)        0       중구     5    115
16       2015-01-01   207       상왕십리(207)        0      성동구     5     74
17       2015-01-01   208  왕십리(성동구청)(208)        0      성동구     5    218
18       2015-01-01   209        한양대(209)        0      성동구     5     38
19       2015-01-01   210         뚝섬(210)        0      성동구     5     95
20       2015-01-01   211         성수(211)        0      성동구     5    125
21       2015-01-01   212       건대입구(212)        0      광진구     5   1595
22       2015-01-01   213         구의(213)        0      광진구     5    226
23       2015-01-01   214         강변(214)        0      광진구     5    356
24       2015-01-01   215       잠실나루(215)        0      송파구     5     67
25       2015-01-01   216         잠실(216)        0      송파구     5   1174
26       2015-01-01   217         신천(217)        0      송파구     5    640
27       2015-01-01   218      종합운동장(218)        0      송파구     5    123
28       2015-01-01   219         삼성(219)        0      강남구     5    295
29       2015-01-01   220         선릉(220)        0      강남구     5    253
...             ...   ...             ...      ...      ...   ...    ...
1914030  2015-12-31   424         명동(424)        1       중구    23    799
1914031  2015-12-31   425         회현(425)        1       중구    23    252
1914032  2015-12-31   426        서울역(426)        1       중구    23    568
1914033  2015-12-31   427       숙대입구(427)        1      용산구    23    578
1914034  2015-12-31   428        삼각지(428)        1      용산구    23    121
1914035  2015-12-31   429        신용산(429)        1      용산구    23    180
1914036  2015-12-31   430         이촌(430)        1      용산구    23    177
1914037  2015-12-31   431         동작(431)        1      동작구    23     69
1914038  2015-12-31   432      총신대입구(432)        1      동작구    23    799
1914039  2015-12-31   433         사당(433)        1      동작구    23    892
1914040  2015-12-31   434        남태령(434)        1      서초구    23     22
1914041  2015-12-31  2519          까치산(5)        1      강서구    23   1468
1914042  2015-12-31  2524        영등포구청(5)        1     영등포구    23     74
1914043  2015-12-31  2532          충정로(5)        1     서대문구    23    107
1914044  2015-12-31  2535         종로3가(5)        1      종로구    23    377
1914045  2015-12-31  2536        을지로4가(5)        1       중구    23     18
1914046  2015-12-31  2541          왕십리(5)        1      성동구    23    158
1914047  2015-12-31  2558              오금        1      송파구    23    123
1914048  2015-12-31  2613           불광(6)        1      은평구    23    184
1914049  2015-12-31  2623           합정(6)        1      마포구    23    434
1914050  2015-12-31  2629          삼각지(6)        1      용산구    23    142
1914051  2015-12-31  2634           약수(6)        1       중구    23     89
1914052  2015-12-31  2636           신당(6)        1       중구    23    124
1914053  2015-12-31  2637          동묘앞(6)        1      종로구    23    262
1914054  2015-12-31  2715           노원(7)        1      노원구    23    746
1914055  2015-12-31  2729         건대입구(7)        1      광진구    23    417
1914056  2015-12-31  2736        고속터미널(7)        1      서초구    23    217
1914057  2015-12-31  2746           대림(7)        1      구로구    23    338
1914058  2015-12-31  2815           잠실(8)        1      송파구    23    222
1914059  2015-12-31  2818         가락시장(8)        1      송파구    23    139

[1914060 rows x 7 columns]

In [13]:
df.merged = pd.merge(df.melted, df.weather, how='left', on=["date", "time"])

In [ ]:
df.merged = pd.merge(df.melted, df.pollution, how='left', on=["date", "time"])

In [14]:
print(df.merged)

               date    id            name category location  time  value   지점  \
0        2015-01-01   150        서울역(150)        0       중구     5    441  108
1        2015-01-01   151         시청(151)        0       중구     5    101  108
2        2015-01-01   152         종각(152)        0      종로구     5    898  108
3        2015-01-01   153       종로3가(153)        0      종로구     5    371  108
4        2015-01-01   154       종로5가(154)        0      종로구     5     57  108
5        2015-01-01   155        동대문(155)        0      종로구     5    130  108
6        2015-01-01   156        신설동(156)        0     동대문구     5     95  108
7        2015-01-01   157        제기동(157)        0     동대문구     5    102  108
8        2015-01-01   158    청량리(지하)(158)        0     동대문구     5    273  108
9        2015-01-01   159        동묘앞(159)        0      종로구     5     48  108
10       2015-01-01   201         시청(201)        0       중구     5     39  108
11       2015-01-01   202      을지로입구(202)        0       중구     5    149  108
12       2015-01-01   203      을지로3가(203)        0       중구     5     30  108
13       2015-01-01   204      을지로4가(204)        0       중구     5     30  108
14       2015-01-01   205  동대문역사문화공원(205)        0       중구     5    125  108
15       2015-01-01   206         신당(206)        0       중구     5    115  108
16       2015-01-01   207       상왕십리(207)        0      성동구     5     74  108
17       2015-01-01   208  왕십리(성동구청)(208)        0      성동구     5    218  108
18       2015-01-01   209        한양대(209)        0      성동구     5     38  108
19       2015-01-01   210         뚝섬(210)        0      성동구     5     95  108
20       2015-01-01   211         성수(211)        0      성동구     5    125  108
21       2015-01-01   212       건대입구(212)        0      광진구     5   1595  108
22       2015-01-01   213         구의(213)        0      광진구     5    226  108
23       2015-01-01   214         강변(214)        0      광진구     5    356  108
24       2015-01-01   215       잠실나루(215)        0      송파구     5     67  108
25       2015-01-01   216         잠실(216)        0      송파구     5   1174  108
26       2015-01-01   217         신천(217)        0      송파구     5    640  108
27       2015-01-01   218      종합운동장(218)        0      송파구     5    123  108
28       2015-01-01   219         삼성(219)        0      강남구     5    295  108
29       2015-01-01   220         선릉(220)        0      강남구     5    253  108
...             ...   ...             ...      ...      ...   ...    ...  ...
1914030  2015-12-31   424         명동(424)        1       중구    23    799  108
1914031  2015-12-31   425         회현(425)        1       중구    23    252  108
1914032  2015-12-31   426        서울역(426)        1       중구    23    568  108
1914033  2015-12-31   427       숙대입구(427)        1      용산구    23    578  108
1914034  2015-12-31   428        삼각지(428)        1      용산구    23    121  108
1914035  2015-12-31   429        신용산(429)        1      용산구    23    180  108
1914036  2015-12-31   430         이촌(430)        1      용산구    23    177  108
1914037  2015-12-31   431         동작(431)        1      동작구    23     69  108
1914038  2015-12-31   432      총신대입구(432)        1      동작구    23    799  108
1914039  2015-12-31   433         사당(433)        1      동작구    23    892  108
1914040  2015-12-31   434        남태령(434)        1      서초구    23     22  108
1914041  2015-12-31  2519          까치산(5)        1      강서구    23   1468  108
1914042  2015-12-31  2524        영등포구청(5)        1     영등포구    23     74  108
1914043  2015-12-31  2532          충정로(5)        1     서대문구    23    107  108
1914044  2015-12-31  2535         종로3가(5)        1      종로구    23    377  108
1914045  2015-12-31  2536        을지로4가(5)        1       중구    23     18  108
1914046  2015-12-31  2541          왕십리(5)        1      성동구    23    158  108
1914047  2015-12-31  2558              오금        1      송파구    23    123  108
1914048  2015-12-31  2613           불광(6)        1      은평구    23    184  108
1914049  2015-12-31  2623           합정(6)        1      마포구    23    434  108
1914050  2015-12-31  2629          삼각지(6)        1      용산구    23    142  108
1914051  2015-12-31  2634           약수(6)        1       중구    23     89  108
1914052  2015-12-31  2636           신당(6)        1       중구    23    124  108
1914053  2015-12-31  2637          동묘앞(6)        1      종로구    23    262  108
1914054  2015-12-31  2715           노원(7)        1      노원구    23    746  108
1914055  2015-12-31  2729         건대입구(7)        1      광진구    23    417  108
1914056  2015-12-31  2736        고속터미널(7)        1      서초구    23    217  108
1914057  2015-12-31  2746           대림(7)        1      구로구    23    338  108
1914058  2015-12-31  2815           잠실(8)        1      송파구    23    222  108
1914059  2015-12-31  2818         가락시장(8)        1      송파구    23    139  108

         기온(°C)  강수량(mm)      ...        운형(운형약어)  최저운고(100m )  시정(10m)  \
0          -9.1      NaN      ...             NaN          NaN   1800.0
1          -9.1      NaN      ...             NaN          NaN   1800.0
2          -9.1      NaN      ...             NaN          NaN   1800.0
3          -9.1      NaN      ...             NaN          NaN   1800.0
4          -9.1      NaN      ...             NaN          NaN   1800.0
5          -9.1      NaN      ...             NaN          NaN   1800.0
6          -9.1      NaN      ...             NaN          NaN   1800.0
7          -9.1      NaN      ...             NaN          NaN   1800.0
8          -9.1      NaN      ...             NaN          NaN   1800.0
9          -9.1      NaN      ...             NaN          NaN   1800.0
10         -9.1      NaN      ...             NaN          NaN   1800.0
11         -9.1      NaN      ...             NaN          NaN   1800.0
12         -9.1      NaN      ...             NaN          NaN   1800.0
13         -9.1      NaN      ...             NaN          NaN   1800.0
14         -9.1      NaN      ...             NaN          NaN   1800.0
15         -9.1      NaN      ...             NaN          NaN   1800.0
16         -9.1      NaN      ...             NaN          NaN   1800.0
17         -9.1      NaN      ...             NaN          NaN   1800.0
18         -9.1      NaN      ...             NaN          NaN   1800.0
19         -9.1      NaN      ...             NaN          NaN   1800.0
20         -9.1      NaN      ...             NaN          NaN   1800.0
21         -9.1      NaN      ...             NaN          NaN   1800.0
22         -9.1      NaN      ...             NaN          NaN   1800.0
23         -9.1      NaN      ...             NaN          NaN   1800.0
24         -9.1      NaN      ...             NaN          NaN   1800.0
25         -9.1      NaN      ...             NaN          NaN   1800.0
26         -9.1      NaN      ...             NaN          NaN   1800.0
27         -9.1      NaN      ...             NaN          NaN   1800.0
28         -9.1      NaN      ...             NaN          NaN   1800.0
29         -9.1      NaN      ...             NaN          NaN   1800.0
...         ...      ...      ...             ...          ...      ...
1914030    -1.6      NaN      ...             NaN          NaN    500.0
1914031    -1.6      NaN      ...             NaN          NaN    500.0
1914032    -1.6      NaN      ...             NaN          NaN    500.0
1914033    -1.6      NaN      ...             NaN          NaN    500.0
1914034    -1.6      NaN      ...             NaN          NaN    500.0
1914035    -1.6      NaN      ...             NaN          NaN    500.0
1914036    -1.6      NaN      ...             NaN          NaN    500.0
1914037    -1.6      NaN      ...             NaN          NaN    500.0
1914038    -1.6      NaN      ...             NaN          NaN    500.0
1914039    -1.6      NaN      ...             NaN          NaN    500.0
1914040    -1.6      NaN      ...             NaN          NaN    500.0
1914041    -1.6      NaN      ...             NaN          NaN    500.0
1914042    -1.6      NaN      ...             NaN          NaN    500.0
1914043    -1.6      NaN      ...             NaN          NaN    500.0
1914044    -1.6      NaN      ...             NaN          NaN    500.0
1914045    -1.6      NaN      ...             NaN          NaN    500.0
1914046    -1.6      NaN      ...             NaN          NaN    500.0
1914047    -1.6      NaN      ...             NaN          NaN    500.0
1914048    -1.6      NaN      ...             NaN          NaN    500.0
1914049    -1.6      NaN      ...             NaN          NaN    500.0
1914050    -1.6      NaN      ...             NaN          NaN    500.0
1914051    -1.6      NaN      ...             NaN          NaN    500.0
1914052    -1.6      NaN      ...             NaN          NaN    500.0
1914053    -1.6      NaN      ...             NaN          NaN    500.0
1914054    -1.6      NaN      ...             NaN          NaN    500.0
1914055    -1.6      NaN      ...             NaN          NaN    500.0
1914056    -1.6      NaN      ...             NaN          NaN    500.0
1914057    -1.6      NaN      ...             NaN          NaN    500.0
1914058    -1.6      NaN      ...             NaN          NaN    500.0
1914059    -1.6      NaN      ...             NaN          NaN    500.0

         지면상태(지면상태코드)  현상번호(국내식)  지면온도(°C)  5cm 지중온도(°C)  10cm 지중온도(°C)  \
0                 NaN        NaN      -6.3          -4.7           -2.4
1                 NaN        NaN      -6.3          -4.7           -2.4
2                 NaN        NaN      -6.3          -4.7           -2.4
3                 NaN        NaN      -6.3          -4.7           -2.4
4                 NaN        NaN      -6.3          -4.7           -2.4
5                 NaN        NaN      -6.3          -4.7           -2.4
6                 NaN        NaN      -6.3          -4.7           -2.4
7                 NaN        NaN      -6.3          -4.7           -2.4
8                 NaN        NaN      -6.3          -4.7           -2.4
9                 NaN        NaN      -6.3          -4.7           -2.4
10                NaN        NaN      -6.3          -4.7           -2.4
11                NaN        NaN      -6.3          -4.7           -2.4
12                NaN        NaN      -6.3          -4.7           -2.4
13                NaN        NaN      -6.3          -4.7           -2.4
14                NaN        NaN      -6.3          -4.7           -2.4
15                NaN        NaN      -6.3          -4.7           -2.4
16                NaN        NaN      -6.3          -4.7           -2.4
17                NaN        NaN      -6.3          -4.7           -2.4
18                NaN        NaN      -6.3          -4.7           -2.4
19                NaN        NaN      -6.3          -4.7           -2.4
20                NaN        NaN      -6.3          -4.7           -2.4
21                NaN        NaN      -6.3          -4.7           -2.4
22                NaN        NaN      -6.3          -4.7           -2.4
23                NaN        NaN      -6.3          -4.7           -2.4
24                NaN        NaN      -6.3          -4.7           -2.4
25                NaN        NaN      -6.3          -4.7           -2.4
26                NaN        NaN      -6.3          -4.7           -2.4
27                NaN        NaN      -6.3          -4.7           -2.4
28                NaN        NaN      -6.3          -4.7           -2.4
29                NaN        NaN      -6.3          -4.7           -2.4
...               ...        ...       ...           ...            ...
1914030           NaN       19.0      -0.7          -0.2            0.1
1914031           NaN       19.0      -0.7          -0.2            0.1
1914032           NaN       19.0      -0.7          -0.2            0.1
1914033           NaN       19.0      -0.7          -0.2            0.1
1914034           NaN       19.0      -0.7          -0.2            0.1
1914035           NaN       19.0      -0.7          -0.2            0.1
1914036           NaN       19.0      -0.7          -0.2            0.1
1914037           NaN       19.0      -0.7          -0.2            0.1
1914038           NaN       19.0      -0.7          -0.2            0.1
1914039           NaN       19.0      -0.7          -0.2            0.1
1914040           NaN       19.0      -0.7          -0.2            0.1
1914041           NaN       19.0      -0.7          -0.2            0.1
1914042           NaN       19.0      -0.7          -0.2            0.1
1914043           NaN       19.0      -0.7          -0.2            0.1
1914044           NaN       19.0      -0.7          -0.2            0.1
1914045           NaN       19.0      -0.7          -0.2            0.1
1914046           NaN       19.0      -0.7          -0.2            0.1
1914047           NaN       19.0      -0.7          -0.2            0.1
1914048           NaN       19.0      -0.7          -0.2            0.1
1914049           NaN       19.0      -0.7          -0.2            0.1
1914050           NaN       19.0      -0.7          -0.2            0.1
1914051           NaN       19.0      -0.7          -0.2            0.1
1914052           NaN       19.0      -0.7          -0.2            0.1
1914053           NaN       19.0      -0.7          -0.2            0.1
1914054           NaN       19.0      -0.7          -0.2            0.1
1914055           NaN       19.0      -0.7          -0.2            0.1
1914056           NaN       19.0      -0.7          -0.2            0.1
1914057           NaN       19.0      -0.7          -0.2            0.1
1914058           NaN       19.0      -0.7          -0.2            0.1
1914059           NaN       19.0      -0.7          -0.2            0.1

         20cm 지중온도(°C)  30cm 지중온도(°C)
0                  0.0            0.7
1                  0.0            0.7
2                  0.0            0.7
3                  0.0            0.7
4                  0.0            0.7
5                  0.0            0.7
6                  0.0            0.7
7                  0.0            0.7
8                  0.0            0.7
9                  0.0            0.7
10                 0.0            0.7
11                 0.0            0.7
12                 0.0            0.7
13                 0.0            0.7
14                 0.0            0.7
15                 0.0            0.7
16                 0.0            0.7
17                 0.0            0.7
18                 0.0            0.7
19                 0.0            0.7
20                 0.0            0.7
21                 0.0            0.7
22                 0.0            0.7
23                 0.0            0.7
24                 0.0            0.7
25                 0.0            0.7
26                 0.0            0.7
27                 0.0            0.7
28                 0.0            0.7
29                 0.0            0.7
...                ...            ...
1914030            1.3            1.9
1914031            1.3            1.9
1914032            1.3            1.9
1914033            1.3            1.9
1914034            1.3            1.9
1914035            1.3            1.9
1914036            1.3            1.9
1914037            1.3            1.9
1914038            1.3            1.9
1914039            1.3            1.9
1914040            1.3            1.9
1914041            1.3            1.9
1914042            1.3            1.9
1914043            1.3            1.9
1914044            1.3            1.9
1914045            1.3            1.9
1914046            1.3            1.9
1914047            1.3            1.9
1914048            1.3            1.9
1914049            1.3            1.9
1914050            1.3            1.9
1914051            1.3            1.9
1914052            1.3            1.9
1914053            1.3            1.9
1914054            1.3            1.9
1914055            1.3            1.9
1914056            1.3            1.9
1914057            1.3            1.9
1914058            1.3            1.9
1914059            1.3            1.9

[1914060 rows x 33 columns]

In [15]:
df.merged = df.merged.fillna(0)

In [ ]:
#df.merged.loc[df.merged['category']=='승차','category'] = 0

In [ ]:
#df.merged.loc[df.merged['category']=='하차','category'] = 1

In [ ]:
df.melted.loc[0,'date'] == df.weather.loc[0,'date']

In [ ]:
print(df.melted.loc[0,'time']) 
print(df.weather.loc[5,'time'])
df.melted.loc[0,'time'].to_numeric== df.weather.loc[5,'time']

In [ ]:
#pd.isna(merged['지점']).sum()

In [ ]:
#merged=merged[pd.isna(merged['지점'])]

In [16]:
df.merged.columns

Index([         u'date',            u'id',          u'name',      u'category',
            u'location',          u'time',         u'value',            u'지점',
              u'기온(°C)',       u'강수량(mm)',       u'풍속(m/s)',      u'풍향(16방위)',
               u'습도(%)',      u'증기압(hPa)',     u'이슬점온도(°C)',     u'현지기압(hPa)',
           u'해면기압(hPa)',        u'일조(hr)',     u'일사(MJ/m2)',        u'적설(cm)',
          u'3시간신적설(cm)',     u'전운량(10분위)',   u'중하층운량(10분위)',      u'운형(운형약어)',
         u'최저운고(100m )',       u'시정(10m)',  u'지면상태(지면상태코드)',     u'현상번호(국내식)',
            u'지면온도(°C)',  u'5cm 지중온도(°C)', u'10cm 지중온도(°C)', u'20cm 지중온도(°C)',
       u'30cm 지중온도(°C)'],
      dtype='object')

In [17]:
#df.X = df.merged.iloc[:,[3,4,7,8,9,11,16,17,18]]
df.X = df.merged.iloc[:,[3,5,8,9,10,12,17,18,19]]
#df.training.X.columns

In [18]:
#df.Y=df.merged.iloc[:,5]
df.Y=df.merged.iloc[:,6]

In [19]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [20]:
lm = LinearRegression()

In [21]:
X_train, X_test, y_train, y_test = train_test_split(df.X, df.Y, test_size=0.25, random_state=1)

In [22]:
print(X_train)

        category  time  기온(°C)  강수량(mm)  풍속(m/s)  습도(%)  일조(hr)  일사(MJ/m2)  \
1310660        0    18     0.8      0.0      3.2   59.0     0.1       0.04
350848         0     8    16.3      0.1      2.8   89.0     0.0       0.06
64022          1     5     4.1      0.0      0.2   61.0     0.0       0.00
1687687        1    21    24.0      0.0      2.5   57.0     0.0       0.00
1484566        1    19    25.5      0.0      4.0   57.0     1.0       0.50
1895516        1    23    26.4      0.0      1.3   72.0     0.0       0.00
62182          1     5     3.6      0.0      1.8   84.0     0.0       0.00
1014010        0    15    12.0      0.0      3.4   22.0     0.3       1.10
1273450        1    17    14.6      0.0      6.9   48.0     0.0       0.25
1015782        0    15     6.2      0.0      6.8   29.0     1.0       2.15
110213         0     6     7.1      0.0      1.1   33.0     0.0       0.00
748862         0    12     3.8      0.0      1.0   34.0     0.0       0.51
1207825        1    16     4.4      0.0      4.3   56.0     0.8       0.65
92533          1     5     7.2      0.0      0.2   58.0     0.0       0.00
72419          1     5    19.0      0.0      2.5   80.0     0.0       0.00
1745375        0    22    15.6      0.0      1.0   75.0     0.0       0.00
1451029        0    19     5.6      0.0      5.4   62.0     0.0       0.00
1439154        0    19    27.1      0.0      4.8   57.0     0.0       0.14
357121         1     8    -5.1      0.0      2.0   62.0     0.0       0.02
21345          0     5    20.6      0.0      1.3   85.0     0.0       0.00
1039795        0    15    29.8      0.0      3.1   31.0     1.0       1.99
880996         1    13    30.1      0.0      2.6   44.0     1.0       2.70
228449         0     7    21.2      0.0      1.8   84.0     0.1       0.13
676920         1    11    28.8      0.0      1.1   36.0     1.0       2.53
27654          0     5    25.2      0.0      1.5   89.0     0.0       0.00
714708         0    12    13.2      0.0      5.6   19.0     1.0       2.27
721734         0    12    18.8      0.0      2.6   40.0     1.0       2.90
398046         1     8    -2.9      0.0      4.3   70.0     0.1       0.05
300322         1     7    -6.6      0.0      2.0   62.0     0.0       0.00
1017870        0    15    15.6      0.0      1.9   48.0     1.0       2.12
...          ...   ...     ...      ...      ...    ...     ...        ...
246322         0     7     1.4      0.0      2.7   72.0     0.0       0.01
1005966        1    14     3.7      0.0      2.5   81.0     0.0       0.53
188317         1     6    14.6      0.0      2.3   61.0     0.0       0.00
365212         1     8     9.8      0.0      4.2   66.0     0.0       0.14
806378         0    13     4.2      0.0      2.6   59.0     0.1       0.78
401660         1     8    -1.5      0.0      2.9   91.0     0.0       0.02
1506187        1    19    -3.3      0.0      3.2   64.0     0.0       0.00
575956         1    10    23.3      0.0      1.8   54.0     0.3       1.21
691090         1    11    23.9      0.0      1.1   62.0     0.9       1.61
1225061        0    17    23.9      0.0      5.7   27.0     1.0       1.62
1070334        1    15    20.7      0.0      4.2   49.0     0.3       0.81
513300         0    10    10.2      0.0      3.9   41.0     1.0       1.54
1041586        0    15    21.0      0.0      3.6   40.0     1.0       1.60
1215878        0    17     6.2      0.0      0.9   35.0     0.0       0.34
1341948        0    18    25.1      0.0      4.4   48.0     1.0       0.46
1485549        1    19    26.9      0.0      3.9   56.0     0.1       0.39
925255         0    14    30.2      0.0      2.3   40.0     1.0       2.34
966604         1    14     5.6      0.0      6.1   50.0     1.0       1.04
413825         0     9    11.1      0.0      4.7   63.0     0.0       0.45
229520         0     7    25.6      0.0      3.3   76.0     0.0       0.15
1070016        1    15    20.5      0.0      5.1   23.0     1.0       2.22
1166159        1    16    11.7      0.0      4.7   24.0     0.6       1.08
73349          1     5    20.2      0.0      2.7   85.0     0.0       0.00
371403         1     8    15.6      0.0      1.4   61.0     1.0       0.90
836489         0    13    25.2      0.0      1.8   48.0     0.3       1.03
491263         1     9    14.4      0.0      0.9   40.0     1.0       1.14
1840200        0    23    21.0      0.0      4.0   93.0     0.0       0.00
470924         1     9    15.9      0.0      0.9   63.0     1.0       1.36
491755         1     9    16.6      0.0      1.2   57.0     1.0       0.96
128037         0     6    23.1      0.0      0.9   88.0     0.0       0.01

         적설(cm)
1310660     0.0
350848      0.0
64022       0.0
1687687     0.0
1484566     0.0
1895516     0.0
62182       0.0
1014010     0.0
1273450     0.0
1015782     0.0
110213      0.0
748862      0.0
1207825     0.0
92533       0.0
72419       0.0
1745375     0.0
1451029     0.0
1439154     0.0
357121      0.0
21345       0.0
1039795     0.0
880996      0.0
228449      0.0
676920      0.0
27654       0.0
714708      0.0
721734      0.0
398046      0.0
300322      0.0
1017870     0.0
...         ...
246322      0.0
1005966     0.0
188317      0.0
365212      0.0
806378      0.0
401660      0.0
1506187     0.0
575956      0.0
691090      0.0
1225061     0.0
1070334     0.0
513300      0.0
1041586     0.0
1215878     0.0
1341948     0.0
1485549     0.0
925255      0.0
966604      0.0
413825      0.0
229520      0.0
1070016     0.0
1166159     0.0
73349       0.0
371403      0.0
836489      0.0
491263      0.0
1840200     0.0
470924      0.0
491755      0.0
128037      0.0

[1435545 rows x 9 columns]

In [23]:
lm.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [ ]:
lm.get_params

In [25]:
for idx, col_name in enumerate(X_train.columns):
    print("The coefficient for {} is {}".format(col_name, lm.coef_[0][idx]))

IndexError: invalid index to scalar variable.

In [28]:
lm.score(X_test, y_test)

0.018322580155740842

In [27]:
lm.score(X_train, y_train)

0.018089125999963485

In [29]:
from sklearn.metrics import mean_squared_error

y_predict = lm.predict(X_test)

regression_model_mse = mean_squared_error(y_predict, y_test)

regression_model_mse

2165833.6284207031